### ISSUE TITLE
With different re-labeling models

### ISSUE THREAD

**Issue by bamiikim** [kaist-dmlab/Prune4Rel#11]
Thanks for the great work. Is Prune4Rel compatible with other re-labeling models? If so, are there any specific considerations to keep in mind when using it with different models?

**Comment by seolachoi** [comment]
Thank you for your kind words!

Yes, Prune4Rel can be compatible with other re-labeling models, but there are a few considerations to keep in mind when using it with different models. Since Prune4Rel is designed to work with noisy label detection and pruning, it's essential that the other re-labeling model can handle noisy data effectively.

You may need to adjust the noise detection thresholds or pruning criteria to align with the behavior of the other model. 
Let me know if you have any other questions!
