### ISSUE TITLE
can it be applied to object detection dataset?

### ISSUE THREAD

**Issue by SeonghyunPark-DM** [kaist-dmlab/Prune4Rel#12]
Would it be possible to apply this research to the labeling of an object detection dataset?

**Comment by seolachoi** [comment]
While Prune4Rel is challenging to apply directly to object detection due to bbox labeling, it can be extended to basic detection tasks that focus on classification. Handling noisy bbox labels would require additional adjustments for more complex detection tasks.

Let me know if you have more questions!
