### ISSUE TITLE
How long does it take to prune ImageNet-21K

### ISSUE THREAD

**Issue by orangingq** [kaist-dmlab/Prune4Rel#6]
Hi, I wanted to ask if you’ve tried using the ImageNet-21k dataset. 
If so, it would be very helpful if you could let me know how long it takes to prune a large dataset like ImageNet-21k.

**Comment by seolachoi** [comment]
Hello,
I haven’t personally tried pruning the ImageNet-21k dataset due to computational resource limitations. However, our paper includes a time analysis that provides some insights into the computational cost of pruning large datasets. I would suggest referring to that section for a better understanding of the time involved.
